using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SkeletonSkills : MonoBehaviour
{
    public GameObject gameController;
    public GameObject player;

    public Stat skeletonBaseArmor;
    public Stat skeletonBaseAttack;
    public Stat skeletonArmor;
    public Stat skeletonAttack;

    public int skeletonLevel;
    public int shootLevel;
    public int bladeLevel;
    public int armorLevel;
    public int bludgeonLevel;

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.Alpha1))
        {
            SkillOne();
        }

        if (Input.GetKeyDown(KeyCode.Alpha2))
        {
            SkillTwo();
        }

        if (Input.GetKeyDown(KeyCode.Alpha3))
        {
            SkillThree();
        }

        if (Input.GetKeyDown(KeyCode.Alpha4))
        {
            SkillFour();
        }
    }


    public void SkillOne()
    {

    }

    public void SkillTwo()
    {

    }

    public void SkillThree()
    {

    }

    public void SkillFour()
    {
        player.GetComponent<PlayerTransforms>().TransformSkill();
    }


}
