using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class TransformButtonOptions : MonoBehaviour
{
    public GameObject gameManger;
    public GameObject humanButton;
    public GameObject skeletonButton;


    private void OnEnable()
    {
        if (gameManger.GetComponent<PlayerExp>().humanLevel > 0)
        {
            humanButton.SetActive(true);
        }
        else humanButton.SetActive(false);

        if (gameManger.GetComponent<PlayerExp>().skeletonLevel > 0)
        {
            skeletonButton.SetActive(true);
        }
        else skeletonButton.SetActive(false);
    }
}
